application: extrafirms
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "2d"

handlers:

- url: /
  static_files: index.html
  upload: index.html
  mime_type: text/html; charset=UTF-8

- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index\.html
  mime_type: text/html; charset=UTF-8

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "20d"

- url: /(.*\.(html))
  static_files: \1
  upload: (.*\.(html))
  mime_type: text/html; charset=UTF-8

- url: /(.*\.(css))
  static_files: \1
  upload: (.*\.(css))
  mime_type: text/css; charset=UTF-8
  http_headers:
    Vary: Accept-Encoding
  expiration: "10d"


- url: /(.*\.(js))
  static_files: \1
  upload: (.*\.(js))
  mime_type: application/javascript; charset=UTF-8
  expiration: "20d"

- url: /(.*\.(gif|png|jpg|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico))
  expiration: "99d"

- url: /(.*\.pdf)
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)
  expiration: "99d"

- url: /(.*\.(svgg))
  static_files: \1
  upload: (.*\.(svg))
  expiration: "99d"
  mime_type: image/svg+xml

- url: /(.*\.(ttf))
  static_files: \1
  upload: (.*\.(ttf))
  mime_type: font/truetype
  expiration: "99d"

- url: /(.*\.(eot))
  static_files: \1
  upload: (.*\.(eot))
  mime_type: application/vnd.ms-fontobject
  expiration: "99d"

- url: /(.*\.(webm))
  static_files: \1
  upload: (.*\.(webm))
  mime_type: video/webm
  expiration: "99d"

- url: /(.*\.(mp4))
  static_files: \1
  upload: (.*\.(mp4))
  mime_type: video/mp4
  expiration: "99d"


libraries:
- name: webapp2
  version: "2.5.1"